// Pełna baza 100 podnoszących na duchu sentencji
const fortunes = [
  "Najsilniejsze drzewa rosną przy najsilniejszych wiatrach.",
  "Masz w sobie moc, o której przypomnisz sobie dokładnie wtedy, kiedy będzie najbardziej potrzebna.",
  "Burze nie przychodzą po to, żeby zniszczyć Twoje życie, ale po to, żeby oczyścić Twoją drogę.",
  "Jesteś autorką swojej historii — możesz w każdej chwili postawić kropkę i zacząć nowy akapit.",
  "Twoja wartość nie maleje tylko dlatego, że ktoś nie potrafi jej dostrzec.",
  "Blizny to nie dowód słabości, ale dowód na to, że potrafisz się goić.",
  "Nie musisz widzieć całej drogi. Wystarczy, że zrobisz kolejny, jeden mały krok.",
  "To, co wydaje się końcem, bardzo często jest tylko początkiem czegoś zupełnie nowego.",
  "Przetrwałaś już 100% swoich najtrudniejszych dni. Twój bilans sukcesów jest imponujący.",
  "Jesteś o wiele bardziej odporna, niż podpowiada Ci Twój lęk.",
  "Odwaga nie zawsze krzyczy. Czasami to cichy głos na koniec dnia, który mówi: „Spróbuję jutro ponownie”.",
  "Nie możesz kontrolować kierunku wiatru, ale zawsze możesz odpowiednio ustawić żagle.",
  "Złoto topi się w ogniu, by stać się czyste. Ty też wychodzisz z trudności silniejsza.",
  "Twoja wewnętrzna przestrzeń jest nienaruszalna — żaden zewnętrzny chaos nie ma tam stałego dostępu.",
  "Nawet najcięższa zima zawsze, bez wyjątku, ustępuje miejsca wiośnie.",
  "Wszystko, co wartościowe, wymaga czasu, cierpliwości i zaufania do procesu.",
  "Masz prawo się zachwiać, ale pamiętaj, że Twoje korzenie sięgają głęboko.",
  "To, co nosisz w środku, jest silniejsze niż to, co staje przeciwko Tobie.",
  "Twoje emocje są ważne, ale nie są Tobą — jesteś niebem, przez które one tylko przepływają.",
  "Każde „nie” od losu bywa bardzo często ukrytym przekierowaniem na właściwe tory.",
  "Jesteś wystarczająca dokładnie taka, jaka jesteś w tej właśnie sekundzie.",
  "Daj sobie pozwolenie na to, by być nieidealnym dziełem w procesie tworzenia.",
  "Twoja produktywność nie definiuje Twojej ludzkiej wartość.",
  "Bądź dla siebie tak dobra i wyrozumiała, jak byłabyś dla kogoś, kogo najmocniej kochasz.",
  "Odpoczynek to nie nagroda za ciężką pracę — to Twoje fundamentalne prawo.",
  "Możesz kochać siebie i jednocześnie chcieć się zmieniać. Jedno nie wyklucza drugiego.",
  "Twoje granice chronią Twoją energię, a nie ranią innych. Masz prawo je stawiać.",
  "Nic nie musisz udowadniać światu. Wystarczy, że żyjesz w zgodzie ze sobą.",
  "Zwolnij. Świat poczeka, a Twoje zdrowie psychiczne i spokój są bezcenne.",
  "To normalne, że czasem nie wiesz, co robić. Pozwól sobie na niewiedzę.",
  "Przestań karać się za błędy z przeszłości — działałaś wtedy najlepiej, jak potrafiłaś, z wiedzą, którą miałaś.",
  "Twoje ciało to Twój dom, a nie projekt do nieustannego poprawiania.",
  "Zasługujesz na miłość, czułość i szacunek — przede wszystkim od samej siebie.",
  "Mów do siebie szeptem pełnym wsparcia, a nie krzykiem pełnym krytyki.",
  "Nie musisz nosić całego świata na swoich barkach. Odłóż ten ciężar choć na chwilę.",
  "Każdy dzień to nowa szansa na to, by zacząć od nowa, bez bagażu wczorajszych potknięć.",
  "Twoja wrażliwość to nie wada — to Twoja największa supermoc i kompas.",
  "Możesz powiedzieć „nie” rzeczom, które zabierają Ci spokój ducha.",
  "Zaopiekuj się najpierw sobą. Nie nalejesz wody z pustego dzbana.",
  "Jesteś jedyna w swoim rodzaju. Twoja perspektywa i Twoja obecność mają znaczenie.",
  "Natura nigdzie się nie spieszy, a wszystko w niej dzieje się na czas.",
  "Oddychaj. Ten moment jest jedynym, który naprawdę istnieje.",
  "Pozwól rzeczom płynąć naturalnym rytmem. Nie wszystko wymaga Twojej natychmiastowej interwencji.",
  "Pokój nie oznacza braku burzy wokół Ciebie — oznacza spokój w Twoim sercu.",
  "Oczyszczenie przestrzeni wokół siebie przynosi jasność umysłowi.",
  "Wszystko przemija — zarówno to, co trudne, jak i to, co piękne. Przyjmij to z wdzięcznością.",
  "Szukaj piękna w prostych, codziennych rzeczach: kropli deszczu, świetle słońca, łyku ciepłej herbaty.",
  "Kiedy uciszasz umysł, zaczynasz słyszeć odpowiedzi, których tak długo szukałaś.",
  "Zaufaj biegowi wydarzeń. Wszechświat ma tendencję do układania się w harmonijną całość.",
  "Żyj tak, by Twoje wnętrze było pełne ładu i czystego światła.",
  "Energia podąża za Twoją uwagą — skupiaj ją na tym, co Cię karmi i buduje.",
  "Cisza nie jest pusta. Jest pełna odpowiedzi.",
  "Bądź jak woda: miękka, elastyczna, ale zdolna drążyć najtwardsze skały.",
  "Każda chwila uważności to krok w stronę głębokiego ukojenia.",
  "Nie goń za rzeczami, które zakłócają Twój wewnętrzny ekosystem.",
  "Harmonia to nie stan idealny, to ciągły powrót do równowagi po każdym zachwianiu.",
  "Your życie staje się lżejsze, kiedy przestajesz walczyć z tym, na co nie masz wpływu.",
  "Znajdź swój własny, nieśpieszny rytm i nie daj się z niego wybić chaosowi świata.",
  "Najpiękniejsze rzeczy rodzą się w ciszy i skupieniu.",
  "Otaczaj się tym, co wnosi do Twojego życia lekkość, świeżość i naturalne piękno.",
  "Tworzenie to akt odwagi. Każda Twoja kreacja zmienia świat na lepsze.",
  "Twój unikalny głos i styl są potrzebne — nikt inny nie widzi świata dokładnie tak jak Ty.",
  "Proces jest ważniejszy niż idealny rezultat końcowy. Czerp radość z samej drogi.",
  "Każda pusta kartka, płótno czy przestrzeń to nie powód do lęku, ale obietnica nieskończonych możliwości.",
  "Twoje talenty nie zostały Ci dane przez przypadek — używaj ich, by wnosić światło.",
  "Sukces to nie cel, do którego biegniesz, ale sposób, w jaki idziesz przez życie.",
  "Twoja wyobraźnia to najwspanialsze narzędzie transformacji rzeczywistości, jakie posiadasz.",
  "Nie bój się tworzyć rzeczy, które są inne, nieszablonowe i całkowicie Twoje.",
  "Inspiracja jest wszędzie wokół nas — wystarczy zwolnić i spojrzeć na świat świeżym okiem.",
  "Każde wielkie dzieło zaczynało się od jednej, małej i niepewnej myśli.",
  "Twoja pasja to paliwo dla Twojej profesji i duszy — nigdy nie pozwól jej zgasnąć.",
  "Projektuj swoje życie z taką samą dbałością o detal i harmonię, z jaką tworzysz swoje najlepsze projekty.",
  "Popełnianie błędów w sztuce i życiu to po prostu zbieranie cennych danych do kolejnej próby.",
  "Twoja wrażliwość estetyczna to dar, który pozwala Ci widzieć magię tam, gdzie inni widzą zwyczajność.",
  "Nie porównuj swojego początku z czyimś środkiem drogi. Twój proces ma własną linię czasu.",
  "Kiedy tworzysz z serca, ludzie to poczują. Autentyczność ma najwyższą wibrację.",
  "Świat profesjonalistów i twórców potrzebuje Twojej wrażliwości, Twoich kolorów i Twoich opowieści.",
  "Masz prawo zmieniać swoje zdanie, swoje plany i swoje artystyczne wizje. Rozwijasz się.",
  "Najbestzym sposobem na przewidzenie przyszłości jest jej samodzielne zaprojektowanie.",
  "Każde doświadczenie, nawet to bolesne, wzbogaca paletę barw, z której możesz tworzyć.",
  "Jutro przyniesie nowe czyste karty, nowe szanse i zupełnie nowe światło.",
  "Najciemniejsza noc przychodzi tuż przed świtem. Światło już do Ciebie idzie.",
  "Wdzięczność za to, co masz teraz, otwiera drzwi dla kolejnych wspaniałych rzeczy.",
  "Małe cuda dzieją się każdego dnia — trzeba tylko pozwolić sobie je zauważyć.",
  "To, co najlepsze w Twoim życiu, wciąż jeszcze czeka na napisanie i przeżycie.",
  "Nic nie truwa wiecznie — ta trudna chwila również minie i zostawi po sobie czyste niebo.",
  "Nadzieja to nie ślepa wiara, to decyzja, by widzieć potencjał dobra w każdym dniu.",
  "Jesteś prowadzona i bezpieczna, nawet gdy mgła na chwilę przysłania Ci horyzont.",
  "Każde dobre słowo, które wysyłasz w świat, wraca do Ciebie pomnożone.",
  "Życie potrafi zaskoczyć pięknem w najmniej oczekiwanym momencie. Bądź na to otwarta.",
  "Twoje serce potrafi pomieścić o wiele więcej radości, niż jesteś w stanie sobie teraz wyobrazić.",
  "Nie bój się marzyć o wielkich rzeczach — wszechświat sprzyja odważnym pragnieniom.",
  "Każdy mały gest dobroci, jaki okazujesz sobie i innym, tworzy fale pozytywnej zmiany.",
  "Patrz w przyszłość z ciekawością, a nie z lękiem. Czeka tam na Ciebie mnóstwo dobra.",
  "Jesteś otoczona niewidzialnym wsparciem, a Twoja intuicja zawsze wskaże Ci właściwy kierunek.",
  "Światło, którego szukasz na zewnątrz, przez cały czas płonie w Twoim wnętrzu.",
  "Z uśmiechem i spokojem przyjmuj to, co przynosi los — wszystko ma swój głębszy sens.",
  "Twoja obecność na tym świecie robi różnicę. Jesteś ważną częścią tej układanki.",
  "Pozwól sobie na luksus optymizmu. To niesamowicie uwalniająca perspektywa.",
  "Wszystko będzie dobrze. A jeśli jeszcze nie jest dobrze, to znaczy, że to jeszcze nie koniec."
];
